# Generated by Django 3.1.1 on 2020-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201211_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asmrvideo',
            name='embed',
            field=models.CharField(max_length=1000),
        ),
    ]
